bases:
  - ../../../../_docs/kustomize/akash-ip-operator

namespace: akash-services

patchesJson6902:
  - path: docker-image.yaml
    target:
      kind: Deployment
      group: apps
      name: akash-ip-operator
      version: v1
