name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - mainnet/main

env:
  MAINNET: ${{ github.ref == 'refs/heads/mainnet/main' || github.base_ref == 'refs/heads/mainnet/main' }}
  AKASH_EVENTBUS_REDIS: "redis:6379"

jobs:

  build-bins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .makerc
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - run: make bins
      - run: make docker-image

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .makerc
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: start redis
        uses: supercharge/redis-github-action@1.4.0
      - run: make test-full

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .makerc
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - name: start redis
        uses: supercharge/redis-github-action@1.4.0
      - run: make test-coverage
      - uses: codecov/codecov-action@v2

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .makerc
      - uses: actions/setup-go@v2
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
      - run: make deps-tidy
      - run: make deps-vendor
      - run: make build
      - name: start redis
        uses: supercharge/redis-github-action@1.4.0
      - run: make test-vet
      - name: lint all
        run: make test-lint-all
      - name: lint make-sublinters
        run: make test-sublinters 
